name: Build Android & Windows and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ----- Install dependencies -----
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # ----- Android Build -----
      - name: Build Android
        run: |
          npm run build
          npx cap sync android
          cd android
          ./gradlew bundleRelease
        shell: bash

      # ----- Windows Build -----
      - name: Install Wine & Electron Builder
        run: |
          sudo apt-get update
          sudo apt-get install -y wine64
          npm install electron-builder --save-dev

      - name: Build Windows EXE
        run: |
          npx electron-builder --win
        shell: bash

      # ----- Create Release -----
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      # ----- Upload Android Build -----
      - name: Upload Android AAB
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: android/app/build/outputs/bundle/release/app-release.aab
          asset_name: app-release.aab
          asset_content_type: application/octet-stream

      # ----- Upload Windows EXE -----
      - name: Upload Windows EXE
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/*.exe
          asset_name: app-release.exe
          asset_content_type: application/octet-stream
